// Code generated by Kitex v0.12.1. DO NOT EDIT.

package stservice

import (
	"context"
	"errors"
	stability "github.com/BeroKiTeer/KitBridge/kitex_gen/thrift/stability"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"testSTReq": kitex.NewMethodInfo(
		testSTReqHandler,
		newSTServiceTestSTReqArgs,
		newSTServiceTestSTReqResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	sTServiceServiceInfo                = NewServiceInfo()
	sTServiceServiceInfoForClient       = NewServiceInfoForClient()
	sTServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return sTServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return sTServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return sTServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "STService"
	handlerType := (*stability.STService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "stability",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.12.1",
		Extra:           extra,
	}
	return svcInfo
}

func testSTReqHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*stability.STServiceTestSTReqArgs)
	realResult := result.(*stability.STServiceTestSTReqResult)
	success, err := handler.(stability.STService).TestSTReq(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newSTServiceTestSTReqArgs() interface{} {
	return stability.NewSTServiceTestSTReqArgs()
}

func newSTServiceTestSTReqResult() interface{} {
	return stability.NewSTServiceTestSTReqResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) TestSTReq(ctx context.Context, req *stability.STRequest) (r *stability.STResponse, err error) {
	var _args stability.STServiceTestSTReqArgs
	_args.Req = req
	var _result stability.STServiceTestSTReqResult
	if err = p.c.Call(ctx, "testSTReq", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
